// Centralized mock event data — used across all pages
export interface Event {
  id: string;
  title: string;
  category: string;
  categoryColor: string;
  image: string;
  date: string;
  time: string;
  venue: string;
  city: string;
  price: number;
  priceMax?: number;
  description: string;
  capacity: number;
  booked: number;
  isFeatured: boolean;
  isHot?: boolean;
  tags: string[];
  coordinator: string;
  coordinatorAvatar: string;
  rating: number;
  ticketTypes: { type: string; price: number; available: number; perks: string[] }[];
}

export const CATEGORIES = [
  { id: 'wedding',    name: 'Weddings',    icon: '💍', color: '#f59e0b', slug: 'wedding'    },
  { id: 'corporate',  name: 'Corporate',   icon: '🏢', color: '#7c3aed', slug: 'corporate'  },
  { id: 'music',      name: 'Music',       icon: '🎵', color: '#22d3ee', slug: 'music'      },
  { id: 'sports',     name: 'Sports',      icon: '⚽', color: '#10b981', slug: 'sports'     },
  { id: 'birthday',   name: 'Birthdays',   icon: '🎂', color: '#ec4899', slug: 'birthday'   },
  { id: 'conference', name: 'Conferences', icon: '📊', color: '#f97316', slug: 'conference' },
  { id: 'concert',    name: 'Concerts',    icon: '🎤', color: '#a855f7', slug: 'concert'    },
  { id: 'custom',     name: 'Custom',      icon: '✨', color: '#06b6d4', slug: 'custom'     },
];

export const EVENTS: Event[] = [
  {
    id: 'evt-001',
    title: 'Grand Royal Wedding Gala',
    category: 'wedding',
    categoryColor: '#f59e0b',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    date: 'May 15, 2025',
    time: '6:00 PM – 11:00 PM',
    venue: 'The Grand Ballroom, Taj Hotel',
    city: 'Mumbai',
    price: 5000,
    priceMax: 15000,
    description: 'An exquisite royal wedding celebration curated with world-class décor, gourmet dining, and live entertainment. Our expert coordinators ensure every detail — from floral arrangements to the reception — is absolutely flawless.',
    capacity: 500,
    booked: 340,
    isFeatured: true,
    isHot: true,
    tags: ['wedding', 'luxury', 'gala', 'royal'],
    coordinator: 'Priya Sharma',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b5fd?w=100&q=80',
    rating: 4.9,
    ticketTypes: [
      { type: 'Standard',  price: 5000,  available: 100, perks: ['General seating', 'Welcome drink', 'Buffet dinner'] },
      { type: 'VIP',       price: 9000,  available: 50,  perks: ['Premium seating', 'Welcome cocktail', 'Fine dining', 'Gift bag'] },
      { type: 'Platinum',  price: 15000, available: 20,  perks: ['Front row seating', 'Open bar', "Chef's table", 'Gift bag', 'Photo with couple'] },
    ],
  },
  {
    id: 'evt-002',
    title: 'TechSummit India 2025',
    category: 'conference',
    categoryColor: '#f97316',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    date: 'June 3, 2025',
    time: '9:00 AM – 6:00 PM',
    venue: 'Bombay Exhibition Centre',
    city: 'Mumbai',
    price: 2500,
    priceMax: 8000,
    description: 'India\'s premier technology conference bringing together 5,000+ founders, engineers, and investors. Featuring keynotes from global tech leaders, product demos, and unparalleled networking opportunities.',
    capacity: 5000,
    booked: 3800,
    isFeatured: true,
    isHot: true,
    tags: ['tech', 'startup', 'networking', 'innovation'],
    coordinator: 'Rahul Verma',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    rating: 4.8,
    ticketTypes: [
      { type: 'Standard', price: 2500, available: 1000, perks: ['All sessions', 'Lunch', 'Networking'] },
      { type: 'VIP',      price: 5500, available: 200,  perks: ['Priority seating', 'Speaker dinner', 'Workshop access', 'Certificate'] },
      { type: 'Platinum', price: 8000, available: 50,   perks: ['Reserved front row', 'Speaker meet', 'VIP lounge', 'All meals', 'Certificate'] },
    ],
  },
  {
    id: 'evt-003',
    title: 'Sunburn Music Festival',
    category: 'concert',
    categoryColor: '#a855f7',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    date: 'June 21, 2025',
    time: '4:00 PM – 2:00 AM',
    venue: 'Magneto Mall Grounds',
    city: 'Pune',
    price: 1500,
    priceMax: 6000,
    description: 'Asia\'s biggest electronic music festival is back! Featuring international DJs, immersive light shows, art installations, and 10,000+ music lovers under the stars.',
    capacity: 10000,
    booked: 7200,
    isFeatured: true,
    tags: ['music', 'EDM', 'festival', 'dj'],
    coordinator: 'Aisha Khan',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
    rating: 4.9,
    ticketTypes: [
      { type: 'General', price: 1500, available: 5000, perks: ['Full day access', 'All stages'] },
      { type: 'VIP',     price: 3500, available: 500,  perks: ['VIP zone', 'Fast entry', 'Drinks package'] },
      { type: 'VVIP',    price: 6000, available: 100,  perks: ['Backstage access', 'Artist meet', 'Open bar', 'Exclusive lounge'] },
    ],
  },
  {
    id: 'evt-004',
    title: 'IPL Watch Party — Finals',
    category: 'sports',
    categoryColor: '#10b981',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80',
    date: 'May 25, 2025',
    time: '7:00 PM – 11:00 PM',
    venue: 'Sky Lounge Terrace, Hyatt',
    city: 'Bangalore',
    price: 1200,
    priceMax: 3500,
    description: 'Watch the IPL finals in style at an exclusive terrace lounge with giant screens, live commentary, unlimited snacks, and the perfect party atmosphere. Limited seats available!',
    capacity: 200,
    booked: 170,
    isFeatured: true,
    isHot: true,
    tags: ['cricket', 'IPL', 'sports', 'party'],
    coordinator: 'Dev Patel',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    rating: 4.7,
    ticketTypes: [
      { type: 'Standard', price: 1200, available: 100, perks: ['Entry', 'Light snacks', 'Soft drinks'] },
      { type: 'Premium',  price: 2200, available: 60,  perks: ['Reserved seat', 'BBQ dinner', 'Beer bucket'] },
      { type: 'Suite',    price: 3500, available: 20,  perks: ['Private suite', 'Open bar', 'Gourmet dinner', 'Match jersey'] },
    ],
  },
  {
    id: 'evt-005',
    title: 'Neon Birthday Bash',
    category: 'birthday',
    categoryColor: '#ec4899',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
    date: 'May 30, 2025',
    time: '8:00 PM – 1:00 AM',
    venue: 'Neon District Club',
    city: 'Delhi',
    price: 2000,
    priceMax: 4500,
    description: 'The ultimate neon-themed birthday party experience with glowing décor, UV lighting, customized cake, DJ night, and a professional photo booth.',
    capacity: 150,
    booked: 90,
    isFeatured: false,
    tags: ['birthday', 'party', 'neon', 'celebration'],
    coordinator: 'Nisha Gupta',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    rating: 4.6,
    ticketTypes: [
      { type: 'Party Pass', price: 2000, available: 80,  perks: ['Entry', 'Welcome cocktail', 'Buffet'] },
      { type: 'VIP Pass',   price: 3500, available: 40,  perks: ['Reserved table', 'Bottle service', 'Unlimited food'] },
      { type: 'Ultra VIP',  price: 4500, available: 10,  perks: ['Host table', 'Premium bottles', 'Photo package', 'Birthday cake slice'] },
    ],
  },
  {
    id: 'evt-006',
    title: 'Corporate Leadership Summit',
    category: 'corporate',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
    date: 'July 10, 2025',
    time: '10:00 AM – 5:00 PM',
    venue: 'ITC Grand Chola',
    city: 'Chennai',
    price: 4500,
    priceMax: 12000,
    description: 'A premium corporate summit for C-suite executives and senior management. Exclusive sessions on leadership, innovation strategy, and business transformation led by Fortune 500 CEOs.',
    capacity: 300,
    booked: 220,
    isFeatured: false,
    tags: ['corporate', 'leadership', 'executive', 'summit'],
    coordinator: 'Karan Mehta',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    rating: 4.8,
    ticketTypes: [
      { type: 'Executive', price: 4500, available: 150, perks: ['All sessions', 'Lunch', 'Certificate'] },
      { type: 'Director',  price: 8000, available: 80,  perks: ['Priority seating', 'Speaker dinner', 'Networking cocktails', 'Certificate'] },
      { type: 'CEO Suite', price: 12000, available: 30, perks: ['Front row', 'Private meetup', 'Gala dinner', 'Annual membership'] },
    ],
  },
  {
    id: 'evt-007',
    title: 'Sufi Music Night',
    category: 'music',
    categoryColor: '#22d3ee',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    date: 'June 14, 2025',
    time: '7:30 PM – 11:00 PM',
    venue: 'Siri Fort Auditorium',
    city: 'Delhi',
    price: 800,
    priceMax: 2500,
    description: 'An enchanting evening of Sufi devotional music featuring celebrated Qawwali maestros and fusion artists. Experience spiritual music in an intimate open-air amphitheater.',
    capacity: 800,
    booked: 580,
    isFeatured: false,
    tags: ['music', 'sufi', 'classical', 'spiritual'],
    coordinator: 'Priya Sharma',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b5fd?w=100&q=80',
    rating: 4.9,
    ticketTypes: [
      { type: 'Gallery',  price: 800,  available: 400, perks: ['Open sitting', 'Evening tea'] },
      { type: 'Balcony',  price: 1500, available: 200, perks: ['Reserved seat', 'Dinner', 'Program booklet'] },
      { type: 'Platinum', price: 2500, available: 50,  perks: ['Front VIP table', 'Artist meet', 'Gourmet dinner', 'Signed CD'] },
    ],
  },
  {
    id: 'evt-008',
    title: 'Startup Founders Mixer',
    category: 'corporate',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80',
    date: 'May 28, 2025',
    time: '6:30 PM – 10:00 PM',
    venue: 'WeWork Galaxy, Koramangala',
    city: 'Bangalore',
    price: 1500,
    priceMax: 3000,
    description: 'An exclusive mixer for startup founders, VCs, and angel investors. Pitch sessions, speed-networking rounds, and fireside chats with unicorn founders.',
    capacity: 400,
    booked: 310,
    isFeatured: false,
    isHot: true,
    tags: ['startup', 'networking', 'vc', 'founders'],
    coordinator: 'Rahul Verma',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    rating: 4.7,
    ticketTypes: [
      { type: 'Founder',  price: 1500, available: 200, perks: ['Full access', 'Starter kit', 'Networking app'] },
      { type: 'Investor', price: 3000, available: 50,  perks: ['Priority access', 'Deal flow list', 'Private dinner', 'VIP badge'] },
    ],
  },
  {
    id: 'evt-009',
    title: 'Goa Beach Wedding',
    category: 'wedding',
    categoryColor: '#f59e0b',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    date: 'December 12, 2025',
    time: '4:00 PM – 12:00 AM',
    venue: 'Sunset Beach Resort',
    city: 'Goa',
    price: 8000,
    priceMax: 20000,
    description: 'A dream beach wedding with sunset ceremony, fairy lights, sand décor, live band, and gourmet seafood dinner under the stars. The most romantic setting on the Goan coast.',
    capacity: 300,
    booked: 180,
    isFeatured: true,
    tags: ['wedding', 'beach', 'destination', 'sunset'],
    coordinator: 'Aisha Khan',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
    rating: 5.0,
    ticketTypes: [
      { type: 'Guest',    price: 8000,  available: 200, perks: ['Ceremony access', 'Gala dinner', 'Beach party'] },
      { type: 'VIP Guest', price: 14000, available: 60, perks: ['Premium seating', 'Welcome cocktail', 'Sunset photoshoot', 'Gift'] },
      { type: 'Suite',    price: 20000, available: 20,  perks: ['Private cabana', 'Butler service', 'Couple portrait', 'Honeymoon gift'] },
    ],
  },
  {
    id: 'evt-010',
    title: 'Rock The Stage — Live Concert',
    category: 'concert',
    categoryColor: '#a855f7',
    image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&q=80',
    date: 'July 4, 2025',
    time: '6:00 PM – 11:00 PM',
    venue: 'NESCO Exhibition Hall',
    city: 'Mumbai',
    price: 999,
    priceMax: 5000,
    description: 'An electrifying live rock concert featuring India\'s top indie bands and surprise international acts. Pyrotechnics, laser shows, and 8,000 fans rocking together.',
    capacity: 8000,
    booked: 6500,
    isFeatured: false,
    isHot: true,
    tags: ['rock', 'live music', 'concert', 'indie'],
    coordinator: 'Dev Patel',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    rating: 4.8,
    ticketTypes: [
      { type: 'Floor',   price: 999,  available: 4000, perks: ['Standing floor access'] },
      { type: 'Seated',  price: 2000, available: 2000, perks: ['Reserved seat', 'Clear view'] },
      { type: 'Backstage', price: 5000, available: 100, perks: ['Backstage tour', 'Artist meet & greet', 'Signed merch'] },
    ],
  },
  {
    id: 'evt-011',
    title: 'AI & Future Tech Expo',
    category: 'conference',
    categoryColor: '#f97316',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    date: 'August 15, 2025',
    time: '9:00 AM – 8:00 PM',
    venue: 'Hyderabad International Convention Centre',
    city: 'Hyderabad',
    price: 3000,
    priceMax: 10000,
    description: 'Explore the future of artificial intelligence, machine learning, and robotics at India\'s largest tech expo. Live demos, hackathons, and 200+ exhibitor booths.',
    capacity: 8000,
    booked: 4200,
    isFeatured: true,
    tags: ['AI', 'tech', 'expo', 'innovation', 'ML'],
    coordinator: 'Karan Mehta',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    rating: 4.7,
    ticketTypes: [
      { type: 'Explorer',  price: 3000, available: 4000, perks: ['Expo access', 'Lunch', 'Demo access'] },
      { type: 'Innovator', price: 6000, available: 800,  perks: ['All sessions', 'Hackathon entry', 'Networking dinner', 'Kit'] },
      { type: 'Visionary', price: 10000, available: 100, perks: ['VIP lounge', 'Speaker dinner', 'Lab access', 'Annual pass'] },
    ],
  },
  {
    id: 'evt-012',
    title: 'Marathon of Champions',
    category: 'sports',
    categoryColor: '#10b981',
    image: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&q=80',
    date: 'September 7, 2025',
    time: '5:30 AM – 12:00 PM',
    venue: 'Jawaharlal Nehru Stadium',
    city: 'Delhi',
    price: 600,
    priceMax: 2000,
    description: 'The city\'s most iconic marathon with 5K, 10K, and Full Marathon categories. Professional timing chips, hydration stations, medals, and the biggest finish line celebration.',
    capacity: 15000,
    booked: 11000,
    isFeatured: false,
    tags: ['marathon', 'run', 'sports', 'fitness'],
    coordinator: 'Nisha Gupta',
    coordinatorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    rating: 4.8,
    ticketTypes: [
      { type: '5K Run',           price: 600,  available: 5000, perks: ['Bib', 'Finisher medal', 'T-shirt'] },
      { type: '10K Run',          price: 1000, available: 5000, perks: ['Bib', 'Finisher medal', 'T-shirt', 'Timing chip'] },
      { type: 'Full Marathon 42K', price: 2000, available: 1500, perks: ['Bib', 'Medal', 'T-shirt', 'Chip', 'Race kit', 'Recovery bag'] },
    ],
  },
];

export const COORDINATORS = [
  {
    id: 'coord-1',
    name: 'Priya Sharma',
    specialty: 'Weddings & Luxury Events',
    city: 'Mumbai',
    rating: 4.9,
    eventsCount: 180,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b5fd?w=200&q=80',
    bio: '10+ years curating India\'s most luxurious wedding experiences.',
  },
  {
    id: 'coord-2',
    name: 'Rahul Verma',
    specialty: 'Tech Conferences & Corporate',
    city: 'Bangalore',
    rating: 4.8,
    eventsCount: 120,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    bio: 'Corporate event specialist with a passion for tech & innovation.',
  },
  {
    id: 'coord-3',
    name: 'Aisha Khan',
    specialty: 'Music Festivals & Concerts',
    city: 'Pune',
    rating: 4.9,
    eventsCount: 95,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    bio: 'Behind India\'s biggest music moments for over 8 years.',
  },
  {
    id: 'coord-4',
    name: 'Dev Patel',
    specialty: 'Sports & Entertainment',
    city: 'Bangalore',
    rating: 4.7,
    eventsCount: 200,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
    bio: 'Sports event veteran who has organized 200+ major events.',
  },
  {
    id: 'coord-5',
    name: 'Nisha Gupta',
    specialty: 'Birthdays & Social Events',
    city: 'Delhi',
    rating: 4.6,
    eventsCount: 310,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    bio: 'Making every celebration unforgettable with creative flair.',
  },
  {
    id: 'coord-6',
    name: 'Karan Mehta',
    specialty: 'Corporate & Executive Events',
    city: 'Chennai',
    rating: 4.8,
    eventsCount: 145,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    bio: 'Trusted by Fortune 500 companies for premium corporate events.',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Ananya Sharma',
    role: 'Bride',
    text: 'Uventere made our dream wedding a reality. Every detail was perfect — from the floral arrangements to the grand reception. Absolutely flawless service!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b5fd?w=80&q=80',
    event: 'Grand Royal Wedding',
  },
  {
    name: 'Rohan Mehta',
    role: 'CEO, TechStart India',
    text: 'The TechSummit was superbly organized. 5,000 attendees, zero hiccups. The networking sessions were invaluable. Will definitely book again!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&q=80',
    event: 'TechSummit India 2025',
  },
  {
    name: 'Zara Khan',
    role: 'Music Blogger',
    text: 'Sunburn was an out-of-this-world experience! The VIP package was worth every rupee — backstage access, artist meetup, and the production was insane!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&q=80',
    event: 'Sunburn Music Festival',
  },
  {
    name: 'Vikram Nair',
    role: 'Startup Founder',
    text: "The Founders Mixer was a goldmine for connections. Met my co-investor there! Uventere's curation of attendees is what sets them apart.",
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&q=80',
    event: 'Startup Founders Mixer',
  },
  {
    name: 'Neha Patel',
    role: 'Marketing Director',
    text: 'Booked the Corporate Leadership Summit for our entire executive team. The seamless booking process and on-ground management were exceptional.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&q=80',
    event: 'Corporate Leadership Summit',
  },
];
